version: '3.8'

services:
  calculator:
    build: .
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/add?num1=1&num2=1"]
      interval: 30s
      timeout: 10s
      retries: 3
