apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080  # Optional: exposed port
